(function(g,h,j){if(!g.SPR)g.SPR={provide:function(a,b){d[a]||(d[a]=b,typeof d[a].init==="function"&&d[a].init())}};var d=g.SPR;d.provide("Common",{random:function(){return Math.floor(Math.random()*8675309)},isArray:function(a){return Array.isArray?Array.isArray(a):Object.prototype.toString.call(a)==="[object Array]"}});d.provide("DOM",{init:function(){d.DOM.on=d.DOM.attachEvent;d.DOM.off=d.DOM.detachEvent},addScript:function(a){var b=h.createElement("script");b.type="text/javascript";b.setAttribute("async",
!0);b.src=a;setTimeout(function(){d.DOM.$("HEAD")[0].appendChild(b)},1);return b},onReady:function(a){h.getElementsByTagName("BODY")[0]?a():g.addEventListener?h.addEventListener("DOMContentLoaded",function(){a()},!1):function(){if(h.uniqueID||!h.expando){var b=h.createElement("document:ready");try{b.doScroll("left"),a()}catch(c){setTimeout(arguments.callee,0)}}}()},attachEvent:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},detachEvent:function(a,b,
c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},top:function(a){return a?a.y?a.y:a.offsetTop+d.DOM.top(a.offsetParent):0},left:function(a){return a?a.x?a.x:a.offsetLeft+d.DOM.left(a.offsetParent):0},height:function(a){return Math.max(a.scrollHeight||0,a.offsetHeight||0,a.clientHeight||0)},width:function(a){return Math.max(a.scrollWidth||0,a.offsetWidth||0,a.clientWidth||0)},scroll:function(){var a=0;return a=g.pageYOffset?g.pageYOffset:h.documentElement?h.documentElement.scrollTop:
0},viewport:function(){var a=0,b=0,b=h.documentElement;if(g.innerWidth)a=g.innerWidth,b=g.innerHeight;else{if(!b||!b.clientWidth)b=d.$("BODY")[0];a=b.clientWidth;b=b.clientHeight}return{w:a,h:b}},$:function(a){var b=[],c,d=0,f;if(!a)return[];if(typeof a!=="string")return[a];switch(a.charAt(0)){case "#":b.push(h.getElementById(a.substring(1)));break;case ".":c=h.getElementsByTagName("*");for(f=" "+a.substring(1)+" ";d<c.length;d+=1)a=(" "+c[d].className+" ").replace(/[\n\t\r]/g," "),a.indexOf(f)>-1&&
b.push(c[d]);break;default:b=h.getElementsByTagName(a)}return b}});d.provide("QS",{escape:function(a){return encodeURIComponent(a)},unescape:function(a){return decodeURIComponent(a)},encode:function(a,b){var c=d.QS,e=[];if(d.Common.isArray(a))for(var f=0,i;f<a.length;f+=1)i=a[f],/\[\]$/.test(b)?e.push(c.escape(b)+"="+c.escape(i)):e.push(c.encode(i,b+"["+(typeof i==="object"?f:"")+"]"));else if(typeof a==="object"&&a!==null&&!("nodeType"in a))for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(b?
e.push(c.encode(a[f],b+"["+f+"]")):e.push(c.encode(a[f],f)));else e.push(c.escape(b)+"="+c.escape(a));return e.join("&")},decode:function(a){var n;var m;for(var b={},c=0,e={"true":!0,"false":!1,"null":null},a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var f=a[c].split("="),i=d.QS.unescape(f[0]),k=b,h=0,g=i.split("]["),l=g.length-1;/\[/.test(g[0])&&/\]$/.test(g[l])?(g[l]=g[l].replace(/\]$/,""),g=g.shift().split("[").concat(g),l=g.length-1):l=0;if(f.length===2)if(m=(f=d.QS.unescape(f[1]))&&!isNaN(f)?
+f:f==="undefined"?void 0:e[f]!==void 0?e[f]:f,f=m,l)for(;h<=l;h+=1)i=g[h]===""?k.length:g[h],n=k[i]=h<l?k[i]||(g[h+1]&&isNaN(g[h+1])?{}:[]):f,k=n;else d.Common.isArray(b[i])?b[i].push(f):b[i]=b[i]!==void 0?[b[i],f]:f;else i&&(b[i]=void 0)}return b}});d.provide("API",{callbacks:{},jsonp:function(a,b,c,e,f){e=e||j;f||(f="cb");var g="cb"+d.Common.random(),k=d.API;c[f]="SPR.API.callbacks."+g;f=h.location.protocol+"//";f==="file://"&&(f="http://");var c=d.QS.encode(c),m=d.DOM.addScript(f+a+b+"?"+c);k.callbacks[g]=
function(a){setTimeout(function(){m.parentNode.removeChild(m)},0);e(a);try{delete k.callbacks[g]}catch(b){k.callbacks[g]=null}}}});d.provide("XD",{callbacks:{},xport:null,init:function(){d.XD.xport=g.postMessage?d.XD.PM:d.XD.Fragment;d.XD.xport.init()},send:function(a,b,c,e){e=e||{};e.__message__=c;d.XD.xport.send(a,b,d.QS.encode(e))},recv:function(a){var a=d.QS.decode(a),b=d.XD.callbacks[a.__message__],c=0;if(b)for(;c<b.length;c+=1)if(typeof b[c]==="function")b[c](a)},on:function(a,b){b=b||j;d.XD.callbacks[a]=
d.XD.callbacks[a]||[];d.XD.callbacks[a].push(b)},once:function(a,b){b=b||j;d.XD.on(a,function(a){b(a);b=j})},PM:{init:function(){d.DOM.attachEvent(g,"message",function(a){d.XD.recv(a.data)})},send:function(a,b,c){a.postMessage(c,h.location.protocol+"//"+b)}},Fragment:{init:function(){},send:function(){}}});d.provide("Cookie",{patterns:{},get:function(a){var b=h.cookie||"",c=d.Cookie.patterns[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),d.Cookie.patterns[a]=
c);return(a=b.match(c))&&d.QS.unescape(a[1])},set:function(a,b,c){var d="";c&&(d="; expires="+c.toGMTString());h.cookie=a+"="+b+d+"; path=/"},del:function(a){d.Cookie.set(a,"",new Date(1982,5,13))}});d.provide("FX",{init:function(){d.FX.Animation.prototype={add:function(a){for(var b,c,e=0;e<a.length;e+=1)c=a[e],b=c.fx?d.FX.Easing[c.fx]:d.FX.Easing.ease,this.queue.push(new d.FX.Tween(this.el.style,c.type,b,c.from,c.to,c.duration,"px"))},run:function(a){for(var b=0,c=this.queue,d=0,f=function(){d+=
1;d===c.length&&typeof a==="function"&&a()};b<c.length;b+=1)c[b].start(f)}};d.FX.Tween.prototype={func:function(a,b,c,d){return c*a/d+b},setTime:function(a){this.prevTime=this._time;a>this._duration?this.looping?(this.rewind(a-this._duration),this.update()):(this._time=this._duration,this.update(),this.stop(),this.callback()):(a<0?this.rewind():this._time=a,this.update())},setPosition:function(a){var b=this.suffixe!==""?this.suffixe:"";this.prevPos=this._pos;this.obj[this.prop]=Math.round(a)+b;this._pos=
a},getPosition:function(a){if(!a)a=this._time;return this.func(a,this.begin,this.change,this._duration)},init:function(a,b,c,e,f,g,h){if(arguments.length){if(h)this.suffixe=h;this.callback=j;this.obj=a;this.prop=b;this.begin=e;this.finish=f;this._pos=e;this._duration=!g||g<=0?1E5:g;this.func=c||d.FX.Easing.none;this.change=f-this.begin}},start:function(a){if(typeof a==="function")this.callback=a;if(!this.begin)this._pos=this.begin=parseInt(this.obj[this.prop],10),this.change=this.finish-this.begin;
this.rewind();this.stop();this.isPlaying=!0;this.onEnterFrame()},rewind:function(a){this.stop();this._time=!a?0:a;this.fixTime();this.update()},update:function(){this.setPosition(this.getPosition(this._time))},onEnterFrame:function(){var a=this;a.isPlaying&&(a.nextFrame(),setTimeout(function(){a.onEnterFrame()},0))},nextFrame:function(){this.setTime((this.getTimer()-this._startTime)/1E3)},stop:function(){this.isPlaying=!1},fixTime:function(){this._startTime=this.getTimer()-this._time*1E3},getTimer:function(){return(new Date).getTime()-
this._time}}},Animation:function(a,b){this.queue=[];this.el=a;this.add(b)},Tween:function(a,b,c,d,f,g,h){this.obj={};this.prop="";this.prevPos=this.prevTime=this.change=0;this.looping=!1;this._finish=this._startTime=this._position=this._pos=this._time=this._duration=0;this.suffixe=this.name="";this.init(a,b,c,d,f,g,h)},Easing:{none:function(a,b,c,d){return c*a/d+b},ease:function(a,b,c,d){return(a/=d/2)<1?c/2*a*a*a*a*a+b:c/2*((a-=2)*a*a*a*a+2)+b},bounce:function(a,b,c,d){var f=0.867;return(a/=d/2)<
1?c/2*a*a*(((f*=1.525)+1)*a-f)+b:c/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+b}}});d.provide("Slide",{domain:"d2sq93p9dgmbhy.cloudfront.net",cdn:"d8rk54i4mohrb.cloudfront.net",api:"hl.simplereach.com",template:"/slides/slide.html?"+d.Common.random(),cookie:"__sruid",optOutCookie:"__spr_opt_out",config:g.__spr_config||{},isHost:!0,recommendations:null,remote:null,hasOpened:!1,evtopts:{},debug:!1,fx:{},init:function(){var a=d.Slide,b=d.Cookie,c=g.navigator.userAgent,e="Spider|crawler|bot|contextad|convera|Microsoft.url|";
e+="Baidu|Bing|Yahoo|Slurp|Holmes|Teoma|Jeeves|libwww|";e+="lwp-trivial|wget|curl|htdig|Ruby|PHP/|urllib|GT::WWW|Snoopy|";e+="PHPCrawl|Nutch|Zend|larbin|ia_archiver|pycurl|iPhone|";e+="iPod|Fennec|IEMobile|Opera Mini|Opera Mobi|Minimo|";e+="Mobile Safari|Symbian|SonyEricsson|Skyfire";a.config.uid=b.get(d.Slide.cookie);if(/MSIE (\d+\.\d+);/.test(navigator.userAgent)&&(b=Number(RegExp.$1),b>=6&&b<7))return;if(!/$^/.test(c)&&!RegExp(e).test(c)&&!a.config.no_slide){if(g.location.host===a.domain)a.localInit();
else d.DOM.onReady(function(){a.remoteInit()});c=["recommend","setState","setCookie","help","setOptOut","setOptOutCookie","open","close","slideIn","toggleHelp"];e=0;for(b=function(b){d.XD.on(b,function(c){a[b](c)})};e<c.length;e+=1)b(c[e])}},localInit:function(){var a=d.Slide,b=d.QS;a.isHost=!1;a.domain=b.unescape(g.location.hash.substring(1));a.remote=g.parent},remoteInit:function(){var a=d.DOM,b=d.Slide,c=b.config.loc,e=a.$("body")[0];typeof c==="string"&&c.indexOf("#")===-1&&c.indexOf(".")===-1&&
(c="#"+c);b.content=a.$(c)[0]||e;b.mult=b.content===e?0.55:0.95;b.recommend()},xd:function(a,b){d.XD.send(d.Slide.remote,d.Slide.domain,a,b)},recommend:function(a){var b=d.Slide,c=d.QS,e=d.DOM,f=d.XD,i=d.API;if(b.isHost)i.jsonp(b.api,"/p/n",b.config,function(a){if(a.hl&&a.hl.length!==0){var d=c.escape(g.location.host);b.frame=b.createFrame(h.location.protocol+"//"+b.domain+b.template+"#"+d);b.remote=b.frame.contentWindow;f.once("slide-init",function(c){if(b.config.offset){var d=parseInt(b.config.offset,
10);if(typeof c.start.top!=="undefined")c.start.top=d+"px";if(typeof c.start.bottom!=="undefined")c.start.bottom=d+"px"}b.fx=c;b.setCookie(a.uid);a.pid=b.config.pid;b.evtopts={uid:a.uid,tid:a.tid,pid:b.config.pid,a:a.hl[0].id};b.xd("recommend",{res:a,config:b.config});b.bindEvents()})}});else e.onReady(function(){var c=a.res.hl[0];b.config=a.config;b.hl=c;b.evtopts={uid:a.res.uid,tid:a.res.tid,pid:a.config.pid,a:c.id};e.$("#simplereach-slide-link")[0].href=c.u;e.$("#simplereach-slide-link")[0].innerHTML=
c.t;if(b.config.disallow_opt_out)e.$("#simplereach-slide-help-button")[0].style.display="none";if(b.config.slide_logo===!1)e.$("#logo")[0].style.display="none";if(b.config.header)e.$("#simplereach-slide-title")[0].innerHTML=b.config.header;if(b.config.css)c=h.createElement("link"),c.rel="stylesheet",c.type="text/css",c.href=b.config.css,e.$("HEAD")[0].appendChild(c);b.bindEvents()})},createFrame:function(a){var b=h.createElement("iframe"),c=h.createElement("div");c.setAttribute("id","simplereach-slide-element");
c.style.position="fixed";c.style.left=0;c.style.right=0;c.style.width="100%";c.style.height=0;c.style.zIndex=8675309;c.style.overflow="visible";c.style.bottom=0;b.scrolling="no";b.frameBorder="0";b.src=a;b.style.position="absolute";b.style.display="none";b.style.border="none";c.appendChild(b);d.DOM.$("BODY")[0].appendChild(c);return b},bindEvents:function(){var a=d.Slide,b=d.DOM;if(a.isHost){if(b.on(g,"scroll",a.onScroll),d.Cookie.get(a.optOutCookie)==="true")a.optedOut=!0}else{b.on(b.$("#simplereach-slide-close-button")[0],
"click",function(){a.close({detach:!0})});b.on(b.$("#simplereach-slide-open-button")[0],"click",function(){a.open()});b.on(b.$("#simplereach-slide-help-button")[0],"click",function(){a.help()});b.on(b.$("#simplereach-slide-link")[0],"click",function(){var c="?u="+a.hl.eu+"&"+d.QS.encode(a.evtopts);b.$("#simplereach-slide-link")[0].href=h.location.protocol+"//"+a.api+"/p/c"+c});if(a.config.slide_logo!==!1)b.$("#logo")[0].style.display="block",b.$("#logo-link")[0].href="http://simplereach.com?ref="+
a.domain,b.$("#logo-link-f")[0].href="http://simplereach.com?ref="+a.domain;b.on(b.$("#save")[0],"click",function(){var c=b.$("#opt-out-n")[0].checked;a.setOptOutCookie({tf:c});a.setOptOut();d.API.jsonp(a.api,c?"/p/oo":"/p/oi",a.evtopts)});a.setOptOut();for(var c=0;c<a.hl.st.length;c+=1)a["show_"+a.hl.st[c]]()}},setOptOut:function(a){var b=d.Slide,c=d.DOM;b.isHost?(a=d.Cookie.get(b.optOutCookie)==="true",b.xd("setOptOut",{oo:a})):a?(b.optedOut=a.oo,c.$("#opt-out-y")[0].checked=!b.optedOut,c.$("#opt-out-n")[0].checked=
b.optedOut,b.close({detach:!0},function(){b.optedOut||b.open()})):b.xd("setOptOut",{})},show_fb:function(){var a=d.Slide;if(!a.isHost){var b=d.DOM,c=b.$("#fb-root")[0];b.addScript(h.location.protocol+"//connect.facebook.net/en_US/all.js");c.style.display="block";c.innerHTML='<fb:like href="'+a.hl.u+'" layout="button_count" show-faces="false" action="like" colorscheme="light"></fb:like>';g.fbAsyncInit=function(){g.FB.init({appId:"200433859985229",status:!0,cookie:!0,xfbml:!0})}}},show_tw:function(){var a=
d.Slide;if(!a.isHost){var b=d.DOM,c=b.$("#tw-root")[0],e=h.createElement("a");c.style.display="block";b.addScript(h.location.protocol+"//platform.twitter.com/widgets.js",!0);e.setAttribute("href","http://twitter.com/share");e.setAttribute("class","twitter-share-button");e.setAttribute("data-url",a.hl.su||a.hl.u);e.setAttribute("data-counturl",a.hl.u);e.setAttribute("data-text",a.hl.t);c.appendChild(e)}},show_goog:function(){if(!d.Slide.isHost){var a=d.DOM,b=a.$("#goog-root")[0];b.style.display="block";
b.innerHTML='<g:plusone size="medium" href="'+d.Slide.hl.u+'"></g:plusone>';a.addScript(h.location.protocol+"//apis.google.com/js/plusone.js",!0)}},show_img:function(){var a=d.Slide;if(!a.isHost&&a.hl.i){var b=d.DOM,c=b.$("#icon-link")[0],e=b.$("#simplereach-slide-image")[0];c.style.display="block";c.href=a.hl.u;c.alt=a.hl.t;e.src=h.location.protocol+"//"+a.cdn+a.hl.i;b.on(c,"click",function(){var c="?u="+a.hl.eu+"&"+d.QS.encode(a.evtopts);b.$("#simplereach-slide-link")[0].href=h.location.protocol+
"//"+a.api+"/p/c"+c})}},help:function(){var a=d.Slide,b=d.DOM;a.isHost?a.close({detach:!0},function(){a.toggleHelp({state:"visible"});(new d.FX.Animation(a.frame,a.fx.slideHelp)).run();a.setState({state:"open"})}):(b.$("#simplereach-slide-help-header")[0].innerHTML="OPTIONS FOR "+a.domain.toUpperCase(),a.xd("help"))},onScroll:function(){var a=d.Slide,b=d.DOM,c=b.height(a.content)+b.top(a.content);b.viewport().h*a.mult+b.scroll()>c*a.mult?a.open():a.close()},slideIn:function(){var a=d.Slide;if(a.isHost){if(!a.inMotion){var b,
c=new d.FX.Animation(a.frame,a.fx.slideIn),e="open";a.optedOut&&(c.add(a.fx.slideClose),e="closed");a.frame.style.display="block";for(b in a.fx.start)Object.prototype.hasOwnProperty.call(a.fx.start,b)&&(a.frame.style[b]=a.fx.start[b]);a.inMotion=!0;c.run(function(){a.inMotion=!1;a.hasShown=!0;a.setState({state:e});a.optedOut?d.DOM.off(g,"scroll",a.onScroll):(d.API.jsonp(a.api,"/p/i",a.evtopts),a.impression=!0)})}}else a.xd("slideIn")},open:function(a,b){var c=d.Slide;if(c.isHost)if(c.hasShown){if(!c.inMotion&&
c.isClosed&&!c.isOpen){var e=new d.FX.Animation(c.frame,c.fx.slideOpen);c.inMotion=!0;e.run(function(){c.inMotion=!1;c.setState({state:"open"});a&&a.detach&&d.DOM.off(g,"scroll",c.onScroll);if(!c.impression)d.API.jsonp(c.api,"/p/i",c.evtopts),c.impression=!0;b&&b()})}}else c.slideIn();else c.xd("open")},close:function(a,b){var c=d.Slide;if(c.isHost)if(!c.inMotion&&!c.isClosed&&c.isOpen){var e=new d.FX.Animation(c.frame,c.fx.slideClose);c.inMotion=!0;e.run(function(){c.inMotion=!1;c.setState({state:"closed"});
a&&a.detach&&d.DOM.off(g,"scroll",c.onScroll);c.toggleHelp({state:"hidden"});b&&b()})}else c.inMotion||b&&b();else c.xd("close",a)},toggleHelp:function(a){var b=d.Slide,c=d.DOM;if(b.isHost)b.xd("toggleHelp",a);else{var e=c.$("#simplereach-slide-content")[0].style,f=c.$("#simplereach-slide-help-button")[0].style,g=c.$("#simplereach-slide-footer")[0].style,h=c.$("#simplereach-slide-help")[0].style,j=c.$("#simplereach-slide-help-header")[0].style,c=c.$("#simplereach-slide-title")[0].style;if(a.state===
"hidden"){e.display="block";if(!b.config.disallow_opt_out)f.display="block";h.display="none";g.display="block";j.display="none";c.display="block"}else e.display="none",f.display="none",h.display="block",g.display="none",j.display="block",c.display="none"}},setState:function(a){var b=d.Slide,c=d.DOM.$,a=a.state;if(b.isHost){if(a==="closed")b.isClosed=!0,b.isOpen=!1;else if(a==="open")b.isClosed=!1,b.isOpen=!0;b.xd("setState",{state:a})}else if(b=c("#simplereach-slide-close-button")[0],c=c("#simplereach-slide-open-button")[0],
a==="closed")b.style.display="none",c.style.display="block";else if(a==="open")c.style.display="none",b.style.display="block"},setCookie:function(a){var b=d.Slide;d.Cookie.set(b.cookie,a,new Date(2032,5,13));b.isHost&&b.xd("setCookie",{uid:a})},setOptOutCookie:function(a){var b=d.Slide,c=d.Cookie;b.isHost?a.tf?c.set(b.optOutCookie,"true"):c.del(b.optOutCookie):b.xd("setOptOutCookie",a)}})})(window,document,function(){});
