strExtraDiv='<div style="z-index:65533;border: 0px solid #000000; position: absolute; -moz-background-clip: initial; -moz-background-origin: initial; -moz-background-inline-policy: initial; top: -1000px; left: -1000px; visibility:hidden; -moz-opacity:'+(0.99)+'; font-family: Tahoma;"Onmouseout="iclickHideShow(false, false)" onmouseover="iclickHideShow(true, false)" id="extraMainDiv"><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td><div style="margin-left: 0px; width: 99%; overflow: hidden;" name="extraAdzone" id="extraAdzone"> '+' Loading...'+' </div></td></tr></tbody></table></div>';strImprDiv='<div style="top: -500px; left: -500px; visibility: hidden;" id="BAImprDiv"></div><div style="top: -500px; left: -500px; visibility: hidden;" id="BAWatchDiv">Impr</div>';
function CountError(){var d=null;d=document.getElementById('extraAdzone');if(isError==0){err_Top=-1000-findPosY(d);err_Left=-854-findPosX(d);isError=1;}}
function swfTest(_str){return /\/(\w+.swf)\??/.test(_str);}
function SyncAdWatchTime(){var url='http://'+strApp+'/syncElapsed.aspx?'+['blogid='+_blogId,'fid='+_formatId,'adsid='+_adsId,'sec='+secs,'sid='+_sessionId,'rdm='+Math.random()*5].join('&');var rt='<img src="'+url+'" border="0" onError="this.width=0;this.height=0;"/>';var d=document.getElementById('BAWatchDiv');if(d!=null){d.innerHTML=rt;rt=null;}StopTheTimer();}
function changeStyle(_o,_k,_v){if(typeof(_o)!='object'){_o=getById(_o);}if(arguments.length>2){if(_o&&_o.style){_o.style[_k]=_v;}}else if(arguments.length>1){doEach(_k,function(_k2){changeStyle(_o,_k2,this);});}}
function ChangeBG(aryId,action){changeStyle('area_'+aryId,'background',(action=='over'?overColor:outColor));}
function findPosX(obj){var curleft=0;var maxcurleft=0;if(obj.offsetParent){while(obj.offsetParent){curleft+=obj.offsetLeft;obj=obj.offsetParent;}}else if(obj.x)curleft+=obj.x;if(curleft>document.body.scrollWidth/2){curleft=curleft-iCliCKWidth;}else{curleft=curleft+145;}return curleft+err_Left;}
function findPosY(obj){var curtop=0;var screenY=0;var maxcurtop=0;if(obj.offsetParent){while(obj.offsetParent){curtop+=obj.offsetTop;obj=obj.offsetParent;}}else if(obj.y)curtop+=obj.y;return curtop+err_Top;}
function iclickIsNavigatorValid(){if(document.getElementById)return true;return false;}
function iclickHideShow(doShow,now){if(!iclickIsNavigatorValid()){return;}{clearTimeout(iclickTimeoutHide);if(!doShow){iclickTimeoutHide=setTimeout("iclickClose()",500);}}}
function iclickClose(){SyncAdWatchTime();if(!iclickIsNavigatorValid())return;changeStyle('extraMainDiv','visibility','hidden');if(document.getElementById('bannerRight_extra')){document.getElementById('bannerRight_extra').innerHTML='';}iclickHidden=true;secs=0;}
function iclickOpen(aryId){iCliCKWidth=aryBloggerAds[aryId][9];iCliCKHeight=aryBloggerAds[aryId][10];objL=document.getElementById('BloggerAdsArea_'+aryId);var _extra='extraMainDiv';changeStyle(_extra,{zIndex:100,top:findPosY(objL)+'px',left:findPosX(objL)+'px',width:iCliCKWidth+'px',height:iCliCKHeight+'px',visibility:'visible'});iclickHidden=false;}
function iCliCKViewCustomAd(aryId){var rt="";rt='<div id="CustomDiv">'+'<iframe id="CustomiFrameAds" src="'+aryBloggerAds[aryId][8]+'" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0" width="'+aryBloggerAds[aryId][9]+'" height="'+aryBloggerAds[aryId][10]+'"></iframe></div>';var d=null;d=document.getElementById('extraAdzone');if(d!=null){d.innerHTML=rt;rt=null;}}
function iCliCKViewAd(){var rt="";rt='<div id="MovieDiv">'+'<table><tr><td><div id="bannerRight_extra">Loading...</div></td></tr></table></div>';var d=null;d=document.getElementById('extraAdzone');if(d!=null){d.innerHTML=rt;rt=null;}}
function BuildAdsArea(aryId,_adsreadme){var _adBody,_id='format_',_ad=aryBloggerAds[aryId],_p=_ad[4],_c=_ad[5],_w=_ad[6],_h=_ad[7];var m_ovr='onMouseOver=',m_out='onMouseOut=',m_clk='onClick=',_r='<tr ',_rc=_r+'>',_re='</tr>',_d='<td ',_de='</td>',_dv='<div ',_dve='</div>',_sn='<span ',_sne='</span>',w_sta='"window.status=\'',r_tr='return true;',_ba='bloggerads',_baU='BloggerAds',_derd=_de+_re+_rc+_d;if(aryBloggerAds[aryId][1]!='thirdparty'&&aryBloggerAds[aryId][1]!='thirdist'){if(aryBloggerAds[aryId][14]=='1'){_adsreadme=fbReadme(aryId,_c);}else{_adsreadme=_sn+m_clk+'"adClick(\''+_c+'\')">'+_adsreadme+_sne;}AdsBody=_rc+_d+'align="center" '+m_ovr+'"ChangeBG('+aryId+', \'over\');" '+m_out+'"ChangeBG('+aryId+', \'out\');">'+'<table class="'+_ba+'" cellpadding="5" id="area_'+aryId+'" name="area_'+aryId+'">'+_rc+_d+'class="'+_ba+'_headline" '+m_clk+'"adClick(\''+_c+'\')" '+m_ovr+w_sta+aryBloggerAds[aryId][2]+'\';'+r_tr+'" '+m_out+w_sta+'\';'+r_tr+'">'+aryBloggerAds[aryId][2]+_derd+'align="center" '+m_ovr+w_sta+aryBloggerAds[aryId][2]+'\';'+r_tr+' " '+m_out+w_sta+'\';'+r_tr+'">';switch(aryBloggerAds[aryId][1]){case'picture':{AdsBody+=getImgString(_id+aryId,_p,_w,_h);break;}case'flash':{AdsBody+=_dv+'id="bannerRightParent">'+_dv+'id="'+_baU+'Area_'+aryId+'" name="'+_baU+'Area_'+aryId+'">'+getFlashString(_id+aryId,_p,_w,_h,'getlink='+_c)+_dve+_dve;break;}case'distent':{AdsBody+=_dv+'id="DistentAera" style="width:'+_w+'px; height:'+_h+'px; z-index:6001">'+_dv+'id="'+_baU+'Area_'+aryId+'" name="'+_baU+'Area_'+aryId+'" '+m_ovr+'"iCliCKAction(\'over\',\''+aryId+'\');" '+m_out+'"iCliCKAction(\'out\',\''+aryId+'\');">'+(swfTest(_p)?getFlashString(_id+aryId,_p,_w,_h,'getlink='+_c):getImgString(_id+aryId,_p,_w,_h))+_dve+_dve;break;}}AdsBody+=_derd+'class="'+_ba+'_text" '+m_ovr+w_sta+aryBloggerAds[aryId][2]+'\';clearTimer(fb_timer);'+r_tr+'" '+m_out+w_sta+'\';fb_out('+aryId+');'+r_tr+'">'+_dv+'class="ads_body_text" '+m_clk+'"adClick(\''+_c+'\')"  >'+aryBloggerAds[aryId][3]+_dve+_derd+'class="'+_ba+'_more">'+_adsreadme+_de+_re+'</table>'+_de+_re;}else{AdsBody=_r+_d+'align="center" class="thirdparty" '+m_ovr+'"ChangeBG(\''+aryId+'\', \'over\');" '+m_out+'"ChangeBG(\''+aryId+'\', \'out\');">'+'<ins id="area_'+aryId+'" name="area_'+aryId+'">'+_dv+'id="'+_baU+'Area_'+aryId+'" name="'+_baU+'Area_'+aryId+'" '+m_ovr+'"iCliCKAction(\'over\',\''+aryId+'\');" '+m_out+'"iCliCKAction(\'out\',\''+aryId+'\');">'+getThirdpartyString(_id,aryId,_p,_c,_w,_h)+_dve+'</ins>'+_de+_re;}return AdsBody;}
function fbReadme(_aryId){return'<div class="ba_fb_readme" onMouseOver="fb_over('+_aryId+')" onMouseOut="fb_out('+_aryId+')" onClick="gbClick('+_aryId+')">'+'<span class="ba_fb_ico">'+'<span class="ba_fb_text">'+_fb_readme+'</span>'+'</span>'+(_fb_countShow?'<span class="fb_arrow"></span>'+'<span class="fb_countOuter">'+'<span class="fb_count">'+(aryBloggerAds[_aryId][15]|0)+'</span>'+'</span>':'')+'</div>';}
function getById(_id){return iclickIsNavigatorValid()?document.getElementById(_id):document.all[_id];}
function getByClass(_c,_p){var _elms=[];doEach((_p?_p:document.body).getElementsByTagName('*'),function(){if(this.className==_c){_elms.push(this);}});return _elms;}
function doEach(_o,_f){if(!_o.length||_o.length==0){for(var _i in _o){if(_f.call(_o[_i],_i)===false){break;}}}else{for(var _i=0;_i<_o.length;_i++){if(_f.call(_o[_i],_i)===false){break;}}}return _o;}var fb_timer;var ani_timers=[];var ani_round=[];
function fb_over(_aryId){clearTimer(fb_timer);var _body=getByClass('ads_body_text',getById('area_'+_aryId))[0];ba_animate(_body,0.8,'LRM',function(){var _fb_format;if(_fb_format=getById('fb_format_'+_aryId)){changeStyle(_fb_format,'display','');}else{_body.parentNode.appendChild(getFBArea(_aryId));}});}
function fb_out(_aryId){fb_timer=setTimeout(function(){var _fb_format;if(_fb_format=getById('fb_format_'+_aryId)){changeStyle(_fb_format,'display','none');}ba_show(getByClass('ads_body_text',getById('area_'+_aryId))[0]);},500);}
function clearTimer(_timer){clearTimeout(_timer);_timer=null;}
function height(_o){return _o.clientHeight==0?_o.offsetHeight:_o.clientHeight;}
function width(_o){return _o.clientWidth==0?_o.offsetWidth:_o.clientWidth;}
function ba_animate(_o,_sec,_type,_f){if(ani_round.length!=0){return;}if(!_sec||_sec<0){_sec=0;}var _clip=[0,width(_o),height(_o),0],_step=28,_sec_step=_sec*1000/_step,_w_step=parseInt(_clip[1]/_step),_h_step=parseInt(_clip[2]/_step),_p=_o.parentNode;_sec=0;ani_round=new Array(_step);if(_p.style.display!='block'){changeStyle(_p,{height:_clip[2]+'px',verticalAlign:'top',display:'block'});changeStyle(_o,{width:_clip[1]+'px',height:_clip[2]+'px'});}changeStyle(_o,'position','absolute');this.doEach(ani_round,function(_idx){ani_timers.push(setTimeout(function(){if(/[LRT]B(M?)/.test(_type)){_clip[0]+=_h_step;}if(/L[TBR](M?)/.test(_type)){_clip[1]-=_w_step;}if(/(([LRB]T)|(TBM))/.test(_type)){_clip[2]-=_h_step;}if(/((R[TBL])|LRM)/.test(_type)){_clip[3]+=_w_step;}changeStyle(_o,'clip','rect('+_clip.join('px ')+'px)');ani_round.pop();if(ani_round.length==0){changeStyle(_o,'display','none');if(_f&&typeof(_f)=='function'){_f.call(_o);}}},_sec+=_sec_step));});}
function ba_show(_o){doEach(ani_timers,function(){clearTimer(ani_timers.pop());});changeStyle(_o,{position:'relative',display:''});ani_round=[];}
function getFBArea(_aryId){var _fb_format=document.createElement('div');_fb_format.id='fb_format_'+_aryId;_fb_format.onclick=function(){gbClick(_aryId);};_fb_format.innerHTML=_fb_text;return _fb_format;}
function gbClick(_aryId){window.open(_fb_connection+'?fid='+aryBloggerAds[_aryId][13]+'&blogid='+_blogId);}
function iCliCKAction(action,aryId){switch(action){case'click':extraadClick(aryBloggerAds[aryId][5]);break;case'over':CheckMask();if(checkDivLoaded("extraMainDiv")){clearTimeout(iclickTimeoutHide);CountError();if(iclickHidden){StopTheTimer();}_adsId=aryBloggerAds[aryId][0];iclickOpen(aryId);if(aryBloggerAds[aryId][1]=='distent'){iCliCKViewAd();document.getElementById('bannerRight_extra').innerHTML=getFlashString('extraFlash',aryBloggerAds[aryId][8],aryBloggerAds[aryId][9],aryBloggerAds[aryId][10],"getlink="+aryBloggerAds[aryId][5]);}else if(aryBloggerAds[aryId][1]=='thirdist'){iCliCKViewAd();document.getElementById('bannerRight_extra').innerHTML=getThirdpartyString('extraFlash',aryId,aryBloggerAds[aryId][8],aryBloggerAds[aryId][5],aryBloggerAds[aryId][9],aryBloggerAds[aryId][10]);}else{iCliCKViewCustomAd(aryId);}StartTheTimer();}break;case'out':if(checkDivLoaded("extraMainDiv")){iclickHideShow(false,false);}break;}}
function assignHTML(_adstitle,_adsstats){strAdsHeader='<div id="dotmoreArea"><table class="adszone"><tr><td align="center"><table class="bloggerads" cellpadding="5" id="area_title" name="area_title"><tr><td class="bloggerads_logo" onMouseOver="window.status=\''+_adsstats+'\';return true;" onMouseOut="window.status=\'\';return true;" onClick="adClick(web_address);"><font size="2"><b>'+_adstitle+'</b></font></td></tr></table></td></tr>';strAdsFooter='<tr><td align="center"><table class="bloggerads" id="area_footer" name="area_footer"><tr><td onMouseOver="window.status=\''+_adsstats+'\';return true;" onMouseOut="window.status=\'\';return true;" onClick="adClick(web_address);" style="padding:0px"><img src="'+strLogo+'" border="0"></td></tr></table></td></tr></table></div>';}
function AppendExtraArea(){var d=document.getElementById('extra_area');if(d==null){mask=document.createElement("DIV");mask.id="extra_area";mask.innerHTML=strExtraDiv;document.body.appendChild(mask);}}
function InnerExtraArea(){var d=document.getElementById(strExtra);if(d!=null){d.innerHTML=strExtraDiv;}}
function getFlashString(_id,_src,_width,_height,_flashvar){var _cid='clsid:d27cdb6e-ae6d-11cf-96b8-444553540000',_cbs='http://fpdownload.adobe.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0',_sa='always',_q='high',_wm='transparent',_alg='middle',_typ='application/x-shockwave-flash',_pg='http://adobe.com/go/getflashplayer',_p=function(n,v){return'<PARAM NAME="'+n+'" VALUE="'+v+'"/>';};_flashvar=_flashvar||'';return'<OBJECT classid="'+_cid+'" codebase="'+_cbs+'" width="'+_width+'" height="'+_height+'" id="'+_id+'" align="'+_alg+'">'+_p('allowScriptAccess',_sa)+_p('movie',_src)+_p('quality',_q)+_p('wmode',_wm)+_p('flashvars',_flashvar)+'<embed id="'+_id+'" src="'+_src+'" flashvars="'+_flashvar+'" wmode="'+_wm+'" quality="'+_q+'" width="'+_width+'" height="'+_height+'" align="'+_alg+'" allowScriptAccess="'+_sa+'" type="'+_typ+'" pluginspage="'+_pg+'">'+'</OBJECT>';}
function getImgString(_id,_src,_width,_height){return'<a id="'+_id+'" href="'+_src+'" target="_blank">'+'<img src="'+_src+'" width="'+_width+'" height="'+_height+'" border="0"/>'+'</a>';}
function getThirdpartyString(_id,_aryId,_src,_click,_width,_height){if(swfTest(_src)){return getFlashString(_id+_aryId,_src,_width,_height);}else{return'<iframe id="'+_id+_aryId+'" src="'+_src+'?clickTAG='+encodeURIComponent(_click)+'" width="'+_width+'" height="'+_height+'" frameborder="0" border="0" cellspacing="0" allowtransparency="true" scrolling="no"></iframe>';}}
function CheckMask(){var sURL=window.document.URL.toString();var bsp={isXuite:(sURL.indexOf("xuite.net")>0),isPixnet:(sURL.indexOf("pixnet.net")>0),isRoodo:(sURL.indexOf("roodo.com")>0)};if(bsp.isXuite){if(checkDivLoaded("footer"))AppendExtraArea();}else if(bsp.isPixnet){if(checkDivLoaded("footer"))AppendExtraArea();}else if(bsp.isRoodo){if(checkDivLoaded("footer"))AppendExtraArea();}else if(!checkDivLoaded("extraMainDiv")){if(checkDivLoaded("footer")){AppendExtraArea();}else{InnerExtraArea();}}}
function checkDivLoaded(divname){var d=document.getElementById(divname);if(d!=null){return true;}return false;}
function syncDIV(rt){var d=document.getElementById('BAImprDiv');if(d!=null){d.innerHTML=rt;rt=null;}}